baseURL = "https://colinnash.ca"
defaultContentLanguage = "en"
languageCode = "en"

title = "Colin Nash"

theme = "gokarna-cnash"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
# footer = "The Marauders"
# description = "I'm Colin Nash, a technical writer and user advocate."
avatarURL = "images/cnash-profile.jpg"
AvatarAltText = "avatar"
avatarSize = "size-m"
ShowPostsOnHomePage = "recent"
customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>

  """


[menu]
[[menu.main]]
# Unique identifier for a menu item
identifier = "posts"

url = "/posts/"

# You can add extra information before the name (HTML format is supported), such as icons
pre = ""

# You can add extra information after the name (HTML format is supported), such as icons
post = ""

# Display name
name = "Posts"

# Weights are used to determine the ordering
weight = 1

[[menu.main]]
identifier = "About"
name = "About me"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "Portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 3

[[menu.main]]
identifier = "github"
url = "https://github.com/colinjnash"
weight = 4

# We use feather-icons: https://feathericons.com/
pre = "<span data-feather='github'></span>"

[[menu.main]]
identifier = "Linkedin"
url = "https://www.linkedin.com/in/colin-nash/"
weight = 5

# We use feather-icons: https://feathericons.com/
pre = "<span data-feather='linkedin'></span>"

[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 4
ordered = false
